name: create-test-pr

on:
  workflow_dispatch:

jobs:
  create-test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out test branch
        uses: actions/checkout@v2
        with:
          ref: main-test
          persist-credentials: false

      - name: Make changes
        id: changes
        run: |
          echo >> README.md
          number="${RANDOM}"
          echo "${number}" >> README.md
          echo "::set-output name=number::${number}"

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_KEY }}

      - name: Create pull request
        id: create-pull-request
        uses: peter-evans/create-pull-request@7380612b49221684fefa025244f2ef4008ae50ad
        with:
          token: ${{ steps.generate_token.outputs.token }}
          title: Test Pull Request (${{ steps.changes.outputs.number }})
          commit-message: Test commit.
          branch: test-pr-${{ steps.changes.outputs.number }}
